### ISSUE TITLE
One error when roslaunch dope dope.launch

### ISSUE THREAD

**Issue by Sunchanghao** [yehengchen/DOPE-ROS-D435#6]
Traceback (most recent call last):
  File "/home/sch/catkin_ws/src/DOPE-ROS-D435-master/dope/nodes/dope", line 23, in <module>
    from dope.inference.cuboid import Cuboid3d
ImportError: No module named inference.cuboid

but i can not install cuboid3d..

**Comment by drostifrosti** [comment]
cuboid3d is located under src/dope/inference/, one solution would be to copy the inference/ folder into nodes/ and remove the `dope.` prefix in the imports of the dope python executable

**Comment by HWatchorn** [comment]
I was having this same issue, I copied the inference folder in to nodes/ and it fixed that issue. Now I get this error:
Traceback (most recent call last):
  File "/home/harryw/project_ws/src/dope/nodes/dope", line 25, in <module>
    from inference.detector import ModelData, ObjectDetector
  File "/home/harryw/project_ws/src/dope/nodes/inference/detector.py", line 22, in <module>
    from utils import get_image_grid
ModuleNotFoundError: No module named 'utils'

i tried copying the utils.py into the inference folder but the error remained
